const { string } = require("joi");
const mongoose=require("mongoose");
const Schema=mongoose.Schema;
// so here require passport local mongoose
const passportLocalMongoose=require("passport-local-mongoose");

const userSchema=new Schema({
    email:{
        type:String,
        required:true,
    }
    // we can also add more fields like name age or etc 
    // and username or password is automatically generated by passport mongoose

});

userSchema.plugin(passportLocalMongoose);//implement username password hashing salting and different methods

module.exports=mongoose.model('User',userSchema);